local gui = Instance.new("ScreenGui") 
gui.Parent = game.Players.LocalPlayer.PlayerGui 

-- Notification 

  local Notif = Instance.new("TextLabel")   
 Notif.Text = "Script Activated."   
  Notif.Size = UDim2.new(0, 100, 0, 30)  
  Notif.Position = UDim2.new(0, 250, 0, -31)  
  Notif.BackgroundColor3 = Color3.new(0, 0, 0)  
  Notif.TextColor3 = Color3.new(1, 1, 1)  
  Notif.BackgroundTransparency = 0.50 
  Notif.Visible = false   
  Notif.Parent = gui

-- Instances

-- Run n Walk
local Run = Instance.new("TextButton") 
local Walk = Instance.new("TextButton") 
-- Script Info
local SInfo = Instance.new("TextButton") 
local InfoFrame = Instance.new("Frame") 
local SNInfo = Instance.new("TextLabel") 
local STInfo = Instance.new("TextLabel")
local SOInfo = Instance.new("TextLabel")
-- Script Hub
local SHub = Instance.new("TextButton") 
local SHFrame = Instance.new("Frame") 
local SPage1 = Instance.new("TextLabel") 
local SPage2 = Instance.new("TextLabel")
local C1 = Instance.new("TextButton") 
local C2 = Instance.new("TextButton") 
local S1 = Instance.new("TextButton") 
local S2 = Instance.new("TextButton") 
local S3 = Instance.new("TextButton") 
local S4 = Instance.new("TextButton")
local S5 = Instance.new("TextButton") 
local S6 = Instance.new("TextButton") 
local S7 = Instance.new("TextButton") 
local S8 = Instance.new("TextButton") 
local S9 = Instance.new("TextButton") 
local S10 = Instance.new("TextButton") 
local S11 = Instance.new("TextButton") 

-- Properties 


