local gui = Instance.new("ScreenGui") 
gui.Parent = game.Players.LocalPlayer.PlayerGui 

-- Notification 

  local Notif = Instance.new("TextLabel")   
 Notif.Text = "Script Activated."   
  Notif.Size = UDim2.new(0, 100, 0, 30)  
  Notif.Position = UDim2.new(0, 250, 0, -31)  
  Notif.BackgroundColor3 = Color3.new(0, 0, 0)  
  Notif.TextColor3 = Color3.new(1, 1, 1)  
  Notif.BackgroundTransparency = 0.50 
  Notif.Visible = false   
  Notif.Parent = gui

-- Instances

-- Run n Walk
local Run = Instance.new("TextButton") 
local Walk = Instance.new("TextButton") 
-- Script Info
local SInfo = Instance.new("TextButton") 
local SIExit = Instance.new("TextButton") 
local InfoFrame = Instance.new("Frame") 
local SNInfo = Instance.new("TextLabel") 
local SUThxInfo = Instance.new("TextLabel") 
local STInfo = Instance.new("TextLabel")
local SOInfo = Instance.new("TextLabel")
-- Script Hub
local SHub = Instance.new("TextButton") 
local SHExit = Instance.new("TextButton") 
local SHExit2 = Instance.new("TextButton") 
local NextPage = Instance.new("TextButton") 
local PrevPage = Instance.new("TextButton") 
local NextPage2 = Instance.new("TextButton") 
local PrevButton2 = Instance.new("TextButton") 
local SHFrame1 = Instance.new("Frame")
local SHFrame2 = Instance.new("Frame") 
local SHTFrame = Instance.new("Frame") 
local SPage1 = Instance.new("TextLabel") 
local SPage2 = Instance.new("TextLabel")
local C1 = Instance.new("TextButton") 
local C2 = Instance.new("TextButton") 
local S1 = Instance.new("TextButton") 
local S2 = Instance.new("TextButton") 
local S3 = Instance.new("TextButton") 
local S4 = Instance.new("TextButton")
local S5 = Instance.new("TextButton") 
local S6 = Instance.new("TextButton") 
local S7 = Instance.new("TextButton") 
local S8 = Instance.new("TextButton") 
local S9 = Instance.new("TextButton") 
local S10 = Instance.new("TextButton") 
local S11 = Instance.new("TextButton") 

-- Properties
 
-- Run/Sprint
 Run.Text = "Run"  
  Run.Size = UDim2.new(0, 35, 0, 35)  
  Run.Position = UDim2.new(0, 600, 0, 40)   
  Run.BackgroundColor3 = Color3.new(0, 0, 0)  
  Run.TextColor3 = Color3.new(1, 1, 1)  
  Run.BackgroundTransparency = 0.50 
  Run.Parent = gui 
-- Walk
 Walk.Text = "Walk"  
  Walk.Size = UDim2.new(0, 35, 0, 35)  
  Walk.Position = UDim2.new(0, 600, 0, 40)  
  Walk.BackgroundColor3 = Color3.new(0, 0, 0)  
  Walk.TextColor3 = Color3.new(1, 1, 1)  
  Walk.BackgroundTransparency = 0.50 
 Walk.Visible = false 
  Walk.Parent = gui 
-- Script Info TextButton Name
  SInfo.Text = "P/C:M"  
  SInfo.Size = UDim2.new(0, 100, 0, 30)  
  SInfo.Position = UDim2.new(0, 105, 0, -31)  
  SInfo.BackgroundColor3 = Color3.new(0, 0, 0)  
  SInfo.TextColor3 = Color3.new(1, 1, 1)  
  Sinfo.BackgroundTransparency = 0.5 
  SInfo.Parent = gui 
-- Script Info Frame
 InfoFrame.Size = UDim2.new(0, 600, 0, 250)  
  InfoFrame.Position = UDim2.new(0, 20, 0, 25)  
  InfoFrame.BackgroundColor3 = Color3.new(0, 0, 0)  
  InfoFrame.BackgroundTransparency = 0.50 
  InfoFrame.Visible = false  
  InfoFrame.Parent = gui
-- Script Info Exit TextButton
 SIExit.Text = "Close"  
  SIExit.Size = UDim2.new(0, 100, 0, 30)  
  SIExit.Position = UDim2.new(0, 105, 0, -31)  
  SIExit.BackgroundColor3 = Color3.new(0, 0, 0)  
  SIExit.TextColor3 = Color3.new(1, 1, 1)  
  SIExit.BackgroundTransparency = 0.50   
  SIExit.Parent = InfoFrame
-- Script Name In Script Info
  SNInfo.Text = "Pruject/Cruxion:M"  
  SNInfo.Size = UDim2.new(0, 100, 0, 30)  
  SNInfo.BackgroundTransparency = 1  
  SNInfo.TextColor3 = Color3.new(1, 1, 1)  
  SNInfo.Font = Enum.Font.SourceSansBold  
  SNInfo.FontSize = Enum.FontSize.Size24  
  SNInfo.Position = UDim2.new(0, 0, 0, 0)  
  SNInfo.Parent = InfoFrame 
-- Thank You
  SUThxInfo.Text = "Thank you for using Pruject/Cruxion:M 😈"  
  SUThxInfo.Size = UDim2.new(0, 100, 0, 30)  
  SUThxInfo.BackgroundTransparency = 1  
  SUThxInfo.TextColor3 = Color3.new(1, 1, 1)  
  SUThxInfo.Font = Enum.Font.SourceSansBold  
  SUThxInfo.FontSize = Enum.FontSize.Size24  
  SUThxInfo.Position = UDim2.new(0, 0, 0, 60)  
  SUThxInfo.Parent = InfoFrame 
-- Text 1
 STInfo.Text = "⚠ There may be some bugs in the script but you'll get a hang of it 💀"  
  STInfo.Size = UDim2.new(0, 100, 0, 30)  
  STInfo.BackgroundTransparency = 1  
  STInfo.TextColor3 = Color3.new(1, 1, 1)  
  STInfo.Font = Enum.Font.SourceSansBold  
  STInfo.FontSize = Enum.FontSize.Size24  
  STInfo.Position =UDim2.new(0, 0, 0, 90)  
  STInfo.Parent = InfoFrame
-- Developed by
 SOInfo.Text = "Made by Discord AI Chatbot Clyde, Rok, Credits to the other Script Owners or Devs for the copy and pasted scripts"  
  SOInfo.Size = UDim2.new(1, 0, 1, 0)  
  SOInfo.BackgroundTransparency = 1  
  SOInfo.TextColor3 = Color3.new(215, 30, 30)  
  SOInfo.Font = Enum.Font.SourceSansBold  
  SOInfo.FontSize = Enum.FontSize.Size10  
  SOInfo.Position = UDim2.new(0, -120, 0, 120)  
  SOInfo.Parent = InfoFrame
-- Script Hub
 